allprojects {
    repositories {
        exclusiveContent {
            forRepository {
                maven { url = uri("https://storage.googleapis.com/download.flutter.io") }
            }
            filter {
                includeGroup("io.flutter")
            }
        }
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
